name: "Setup hlslkit"
description: "Setup hlslkit tools for shader compilation and buffer scanning"

inputs:
    python-version:
        description: "Python version to use"
        required: false
        default: "3.11"
    install-fxc:
        description: "Whether to install Windows SDK for fxc.exe"
        required: false
        default: "false"
    cache-key-suffix:
        description: "Additional cache key suffix for pip cache"
        required: false
        default: ""

runs:
    using: "composite"
    steps:
        - name: Setup Poetry environment
          uses: ./.github/actions/setup-poetry-env
          with:
              python-version: ${{ inputs.python-version }}

        - name: Install hlslkit with Poetry
          shell: bash
          run: |
              echo "Installing hlslkit from current directory with Poetry"
              poetry install

        - name: Install Windows SDK (for fxc.exe)
          if: ${{ inputs.install-fxc == 'true' && runner.os == 'Windows' }}
          shell: powershell
          run: |
              # Use established chocolatey action approach
              choco install windows-sdk-10-version-2004-all -y

        - name: Verify hlslkit installation
          shell: bash
          run: |
              poetry run hlslkit-compile --help
              poetry run hlslkit-generate --help
              poetry run hlslkit-buffer-scan --help
